import type { UnitBase } from "./types";

export const ART = {
  skel_soldier: "/image/skel_soldier.png",
  gob_rogue: "/image/gob_rogue.png",
  wisp_mage: "/image/wisp_mage.png",
  orc_brute: "/image/orc_brute.png",
  lich_apprentice: "/image/lich_apprentice.png",
  succubus: "/image/succubus.png",
  dread_knight: "/image/dread_knight.png",
} as const;

export const BLUEPRINTS: UnitBase[] = [
  {
    id: "skel_soldier",
    name: "스켈레톤 전사",
    emoji: "☠️",
    tribe: "언데드",
    role: "탱커",
    rarity: 1,
    hpMax: 420,
    atk: 58,
    speed: 88,
    ultName: "뼈의 벽",
    ultDesc: "보호막 획득",
    img: ART.skel_soldier,
  },
  {
    id: "gob_rogue",
    name: "고블린 도적",
    emoji: "🗡️",
    tribe: "야수",
    role: "딜러",
    rarity: 1,
    hpMax: 300,
    atk: 90,
    speed: 115,
    ultName: "암습 연타",
    ultDesc: "2연타",
    img: ART.gob_rogue,
  },
  {
    id: "wisp_mage",
    name: "공포의 위습",
    emoji: "🜏",
    tribe: "악마",
    role: "마법사",
    rarity: 2,
    hpMax: 280,
    atk: 110,
    speed: 100,
    ultName: "심연의 폭발",
    ultDesc: "광역 피해",
    img: ART.wisp_mage,
  },
  {
    id: "orc_brute",
    name: "오크 분쇄자",
    emoji: "💢",
    tribe: "야수",
    role: "딜러",
    rarity: 2,
    hpMax: 520,
    atk: 140,
    speed: 85,
    ultName: "분쇄 강타",
    ultDesc: "강한 일격",
    img: ART.orc_brute,
  },
  {
    id: "lich_apprentice",
    name: "리치 견습",
    emoji: "🧙‍♂️",
    tribe: "언데드",
    role: "마법사",
    rarity: 3,
    hpMax: 360,
    atk: 140,
    speed: 102,
    ultName: "영혼 흡수",
    ultDesc: "광역+치유",
    img: ART.lich_apprentice,
  },
  {
    id: "succubus",
    name: "황혼의 서큐버스",
    emoji: "🦇",
    tribe: "악마",
    role: "딜러",
    rarity: 4,
    hpMax: 380,
    atk: 165,
    speed: 120,
    ultName: "파멸의 입맞춤",
    ultDesc: "강력 일격",
    img: ART.succubus,
  },
  {
    id: "dread_knight",
    name: "공포의 기사",
    emoji: "🛡️",
    tribe: "언데드",
    role: "탱커",
    rarity: 5,
    hpMax: 720,
    atk: 150,
    speed: 95,
    ultName: "무덤의 서약",
    ultDesc: "전체 보호막",
    img: ART.dread_knight,
  },
];
