import type { UnitBase } from "./types";

export const ENEMIES: UnitBase[] = [
  {
    id: "royal_soldier",
    name: "왕국 병사",
    emoji: "🛡️",
    tribe: "인간",
    role: "탱커",
    rarity: 1,
    hpMax: 380,
    atk: 55,
    speed: 92,
    ultName: "방패 가격",
    ultDesc: "추가 피해",
    img: "/image/royal_soldier.png",
  },
  {
    id: "royal_archer",
    name: "왕국 궁수",
    emoji: "🏹",
    tribe: "인간",
    role: "딜러",
    rarity: 1,
    hpMax: 260,
    atk: 75,
    speed: 112,
    ultName: "집중 사격",
    ultDesc: "단일 강타",
    img: "/image/royal_archer.png",
  },
  {
    id: "temple_wizard",
    name: "성전 마법사",
    emoji: "🔮",
    tribe: "인간",
    role: "마법사",
    rarity: 2,
    hpMax: 300,
    atk: 100,
    speed: 105,
    ultName: "성광 폭발",
    ultDesc: "광역 빛",
    img: "/image/temple_wizard.png",
  },
];
